export const CUSTOM_SENTIMENT_WORDS: Record<string, number> = {
  flimsy: -3,
  luxurious: 4,
  itchy: -2,
  breathable: 3,
  overpriced: -3,
  bargain: 3,
  flattering: 3,
  frumpy: -2,
  stretchy: 2,
  stiff: -1,
  silky: 3,
  scratchy: -2,
  durable: 3,
  flaky: -2,
  seamless: 2,
  bulky: -1,
  comfy: 3,
  uncomfortable: -3,
  lightweight: 2,
  heavy: -1,
  snug: 1,
  baggy: -1,
  stylish: 3,
  chic: 3,
  trendy: 2,
  outdated: -2,
  versatile: 3,
  impractical: -2,
  waterproof: 2,
  shrink: -2,
  pilling: -3,
  fading: -2,
  wrinkle: -1,
  'true to size': 2,
  'runs small': -1,
  'runs large': -1,
  'well-made': 3,
  'poorly-made': -3,
  'high-end': 3,
  'low-quality': -3,
  'long-lasting': 3,
  'wear out': -2,
  'worn out': -2,
  'cheap-looking': -3,
  unraveling: -3,
  'see-through': -2,
  opaque: 1,
  'moisture-wicking': 2,
  clingy: -1,
  'form-fitting': 1,
  roomy: 1,
  'figure-flattering': 3,
};

export const POSITIVE_THRESHOLD = 0.05;
export const NEGATIVE_THRESHOLD = -0.05;
